# Generated by Django 5.2.4 on 2025-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserVerifyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_verify", models.BooleanField(default=False)),
                ("email_hash", models.TextField(blank=True, null=True)),
                ("expired_time", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=5, null=True)),
                ("code_expired_time", models.DateTimeField(blank=True, null=True)),
                ("trying", models.IntegerField(default=0)),
            ],
        ),
    ]
