# Generated by Django 5.2.4 on 2025-07-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userverifyemail_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverifyemail",
            name="email_hash",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
